import type { HubTemplateConfig } from "./types";

export const foodDiningConfig: HubTemplateConfig = {
  template: "food_dining",
  layout: "business",
  variants: ["Restaurant", "Food Truck", "Cloud Kitchen"],
  terminology: {
    hub: "Restaurant / Kitchen / Food Truck",
    deets: "Updates",
    members: "Followers",
    admin: "Owner / Manager",
    about: "Our Story",
  },
  tabs: ["About", "Posts", "Attachments", "Events", "Members"],
  postTypes: [
    { type: "update", icon: "📢", description: "General announcement" },
    { type: "special", icon: "🍽️", description: "Today's special dish" },
    { type: "deal", icon: "💰", description: "Discount or offer" },
    { type: "event", icon: "📅", description: "Live music, themed dinner" },
    { type: "new_dish", icon: "🍔", description: "New menu item" },
    { type: "alert", icon: "⚠️", description: "Closed, delay, urgent" },
  ],
  aboutSections: [
    "Hero Block",
    "Quick Info Strip",
    "Specials Today",
    "Menu Highlights",
    "Our Story",
    "Gallery",
    "Location & Hours",
    "Weekly Schedule",
    "Order & Contact",
  ],
  defaultCTAs: [
    { label: "Order Online", actionType: "url", actionValue: "" },
    { label: "Reserve Table", actionType: "opentable", actionValue: "" },
    { label: "Get Directions", actionType: "maps", actionValue: "" },
  ],
  keyFields: [
    "Variant (Restaurant / Food Truck / Cloud Kitchen)",
    "Cuisine type (multi-select)",
    "Price range ($ / $$ / $$$ / $$$$)",
    "Seating capacity (Restaurant only)",
    "Delivery platforms (DoorDash, UberEats, GrubHub links)",
    "Order link",
    "WhatsApp order number",
    "Reservation link",
    "Weekly hours (Mon-Sun)",
    "Service area zip codes (Cloud Kitchen only)",
    "Truck weekly schedule (Food Truck only)",
  ],
  memberRoles: [
    { role: "Owner", who: "Creator", permissions: "Everything" },
    { role: "Manager", who: "Admin", permissions: "Post all types, respond to reviews" },
    { role: "Follower", who: "Member", permissions: "View, leave reviews" },
  ],
  discoverCard: {
    showCover: true,
    badges: ["Cuisine"],
    showRating: true,
    showButton: true,
    buttonLabel: "Order Now / View Menu",
  },
};
